# --- Стадия сборки ---
FROM node:20-alpine3.19 AS build

RUN apk add --no-cache curl && npm i -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Копируем скрипт и делаем его исполняемым
COPY scripts/entrypoint-build.sh /entrypoint-build.sh
RUN chmod +x /entrypoint-build.sh

CMD ["/entrypoint-build.sh"]