FROM node:20-alpine3.19 AS build

RUN apk add --no-cache curl && npm i -g pnpm localtunnel

WORKDIR /app

COPY scripts/entrypoint-localtunnel.sh /entrypoint-localtunnel.sh

RUN chmod +x /entrypoint-localtunnel.sh

EXPOSE 3000

CMD ["/entrypoint-localtunnel.sh"]
