import { resolveImageSrcSet } from '@/lib/imageSrcSet';

export interface OptimizedImageProps {
  /** Original image path under /images/, e.g. /images/portfolio/hero.jpg */
  src: string;
  alt: string;
  /** Responsive sizes string passed to <source> and <img>. Default: '100vw' */
  sizes?: string;
  /** true → loading="eager" fetchPriority="high"; false → loading="lazy" decoding="async" */
  priority?: boolean;
  width?: number;
  height?: number;
  className?: string;
}

/**
 * Drop-in <img> replacement that uses WebP srcset variants generated by imageResizePlugin.
 * In dev mode (import.meta.env.DEV) the plugin doesn't run, so renders a plain <img> fallback.
 * In production renders <picture><source type="image/webp" srcset="…"><img src="…"></picture>.
 */
export function OptimizedImage({
  src,
  alt,
  sizes = '100vw',
  priority = false,
  width,
  height,
  className,
}: OptimizedImageProps) {
  const loadingProps = priority
    ? ({ loading: 'eager', fetchPriority: 'high' } as const)
    : ({ loading: 'lazy', decoding: 'async' } as const);

  // In dev mode the plugin hasn't generated _optimized files — render plain img
  if (import.meta.env.DEV) {
    return (
      <img
        src={src}
        alt={alt}
        sizes={sizes}
        width={width}
        height={height}
        className={className}
        {...loadingProps}
      />
    );
  }

  const srcset = resolveImageSrcSet(src);

  return (
    <picture>
      {srcset && <source type="image/webp" srcSet={srcset} sizes={sizes} />}
      <img
        src={src}
        alt={alt}
        sizes={sizes}
        width={width}
        height={height}
        className={className}
        {...loadingProps}
      />
    </picture>
  );
}
