version: '3.8'

services:
  rmaster35-web-site-build-test:
    build:
      context: ../../../../../src/apps/web/advertise-agency-site
      dockerfile: Dockerfile-build
      target: build
    container_name: rmaster35-web-site-build-test-container
    networks:
      - rmaster35
    volumes:
      - ./output:/app/output
    environment:
      - NODE_ENV=production
      - STRAPI_SERVICE_URL=${STRAPI_SERVICE_URL}
      - NEXT_PUBLIC_STRAPI_SERVICE_URL=${NEXT_PUBLIC_STRAPI_SERVICE_URL}
      - BREADCRUMBS_SERVICE_URL=${BREADCRUMBS_SERVICE_URL}
      - NEXT_PUBLIC_BREADCRUMBS_SERVICE_URL=${NEXT_PUBLIC_BREADCRUMBS_SERVICE_URL}
      - FORM_DATA_SERVICE_URL=${FORM_DATA_SERVICE_URL}
      - NEXT_PUBLIC_FORM_DATA_SERVICE_URL=${NEXT_PUBLIC_FORM_DATA_SERVICE_URL}
      - YANDEX_COMPANY_ID=${YANDEX_COMPANY_ID}
      - PORTFOLIO_PAGE_SIZE=${PORTFOLIO_PAGE_SIZE}

networks:
  rmaster35:
    external: true
    driver: bridge
