# Используем Node.js LTS-версию
FROM node:20-alpine

# Устанавливаем bash и другие необходимые пакеты
RUN apk add --no-cache bash

# Устанавливаем рабочую директорию
WORKDIR /srv/app

# Устанавливаем Strapi через npx и создаём проект без запуска
RUN npx create-strapi-app@latest . --no-run --quickstart

# Устанавливаем зависимости (так как --quickstart копирует package.json)
RUN npm install

# Открываем порт для Strapi
EXPOSE 1337

# Запуск Strapi в режиме разработки
CMD ["npm", "run", "start"]
